import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TabBar } from "@/components/features/TabBar";
import { NavBar } from "@/components/features/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          margin: 0,
          padding: 0,
          display: "flex",
          justifyContent: "center",
          backgroundColor: "#000",
        }}
      >
        <div
          style={{
            width: "375px",
            minHeight: "811.7px",
            backgroundColor: "#fff",
            position: "relative",
          }}
        >
          <NavBar />
          {children}
          <TabBar />
        </div>
      </body>
    </html>
  );
}
